openapi: 3.1.0
info:
  title: Laravel API Documentation
  version: 1.0.0
  description: This is the API documentation for your Laravel project.
servers:
  - url: http://localhost:8000/api
    description: Local development server

security:
  - BearerAuth: []

paths:
  /posts:
    $ref: "./paths/posts.yml#/paths/~1posts"
  /posts/{post}:
    $ref: "./paths/posts.yml#/paths/~1posts~1{post}"
  /posts/{post}/comments:
    $ref: "./paths/comments.yml#/paths/~1posts~1{post}~1comments"
  /posts/{post}/comments/{comment}:
    $ref: "./paths/comments.yml#/paths/~1posts~1{post}~1comments~1{comment}"
  /register:
    $ref: "./paths/auth.yml#/paths/~1register"
  /login:
    $ref: "./paths/auth.yml#/paths/~1login"
  /logout:
    $ref: "./paths/auth.yml#/paths/~1logout"
  # /users:
  #   $ref: "./paths/users.yml#/paths/~1users"
  # /users/{user}:
  #   $ref: "./paths/users.yml#/paths/~1users~1{user}"
  # I'm missing something in referencing the user path file "JSON Pointer evaluation failed"
  # The dirty fix is having it inline here sadly
  /users: 
    get:
      summary: Get a paginated list of all users
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: A paginated list of users
          content:
            application/json:
              schema:
                $ref: "./schemas/PaginatedUsers.yml"
        "401":
          description: Unauthenticated
        "403":
          description: Forbidden - not authorized

  /users/{user}:
    get:
      summary: Get a user by ID
      parameters:
        - name: user
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: A user object
          content:
            application/json:
              schema:
                $ref: "./schemas/User.yml"
        "401":
          description: Unauthenticated
        "404":
          description: User not found

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Comment:
      $ref: "./schemas/Comment.yml"
    LoginRequest:
      $ref: "./schemas/LoginRequest.yml"
    PaginatedComments:
      $ref: "./schemas/PaginatedComments.yml"
    PaginatedPosts:
      $ref: "./schemas/PaginatedPosts.yml"
    PaginatedUsers:
      $ref: "./schemas/PaginatedUsers.yml"
    Post:
      $ref: "./schemas/Post.yml"
    User:
      $ref: "./schemas/User.yml"
    UserRegistration:
      $ref: "./schemas/UserRegistration.yml"
