version: "3.8"

services:
    app:
        build:
            context: ..
            dockerfile: ./.devcontainer/Dockerfile
        container_name: laravel-app
        ports:
            - "8000:8000"
        volumes:
            - ..:/var/www/html
        depends_on:
            - mysql
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=test_db
            - DB_USERNAME=user
            - DB_PASSWORD=pass

    mysql:
        image: mysql:8.4
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root_pass
            MYSQL_DATABASE: test_db
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql

volumes:
    mysql-data:
